from __future__ import annotations

import os
from dotenv import load_dotenv
from typing import Literal


load_dotenv()


SA_HOST = 'smotret-anime.app'
DATABASE_URL = 'sqlite+aiosqlite:///./db.sqlite3'
PARSING_PROXY_PROVIDER: Literal['scrapedo', 'flaresolverr'] = 'flaresolverr'
FLARESOLVERR_HOST = '127.0.0.1'
FLARESOLVERR_PORT = 8191
FLARESOLVERR_SESSION_POOL_SIZE = 3
FLARESOLVERR_MAX_TIMEOUT_MS = 60000
FLARESOLVERR_HTTP_TIMEOUT_SECONDS = 75.0


ONGOING_EPISODE_CACHE_TTL_HOURS = 2
FINISHED_EPISODE_CACHE_TTL_HOURS = 24
ONGOING_TRANSLATION_CACHE_TTL_HOURS = 2
FINISHED_TRANSLATION_CACHE_TTL_HOURS = 24
VIDEO_CACHE_TTL_HOURS = 2
ANIME_STATUS_CACHE_TTL_HOURS = 24
ANILIST_CACHE_TTL_HOURS = 168
CINEMETA_CACHE_TTL_HOURS = 168
KITSU_MAPPINGS_CACHE_TTL_HOURS = 168

FINISHED_STABLE_AFTER_DAYS = 7
VIDEO_PROBE_TIMEOUT_SECONDS = 10.0
QUALITY_PROFILES = {'hd': 720, 'fhd': 1080, '4k': 2160}

SCRAPE_TOKEN = os.getenv('SCRAPE_TOKEN')
LOGIN = os.environ['LOGIN']
PASSWORD = os.environ['PASSWORD']
ALEMBIC_DATABASE_URL = os.getenv('ALEMBIC_DATABASE_URL')
